/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppDivider: typeof import('./src/components/AppDivider.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppImage: typeof import('./src/components/Authenticated/AppImage.vue')['default']
    AppSnackbar: typeof import('./src/components/AppSnackbar.vue')['default']
    AppToolbar: typeof import('./src/components/AppToolbar.vue')['default']
    DisplayRows: typeof import('./src/components/Authenticated/DisplayRows.vue')['default']
    ImageMetadata: typeof import('./src/components/Authenticated/ImageMetadata.vue')['default']
    PiInfo: typeof import('./src/components/Authenticated/PiInfo.vue')['default']
    PiOffline: typeof import('./src/components/Authenticated/PiOffline.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
